from datetime import UTC, date, datetime
from decimal import Decimal
from typing import Any

ASSETS: list[dict[str, Any]] = [
    {
        "symbol": "AAPL",
        "name": "Apple Inc.",
        "asset_type": "Equity",
        "currency": "USD",
        "sector": "Technology",
        "price": Decimal("213.49"),
        "change_percent": Decimal("1.24"),
        "market_cap": Decimal("3180000000000.00"),
        "pe_ratio": Decimal("33.18"),
        "dividend_yield": Decimal("0.45"),
        "fair_value": Decimal("221.00"),
        "technical_signal": "bullish",
    },
    {
        "symbol": "MSFT",
        "name": "Microsoft Corporation",
        "asset_type": "Equity",
        "currency": "USD",
        "sector": "Technology",
        "price": Decimal("458.17"),
        "change_percent": Decimal("0.62"),
        "market_cap": Decimal("3405000000000.00"),
        "pe_ratio": Decimal("37.42"),
        "dividend_yield": Decimal("0.66"),
        "fair_value": Decimal("472.00"),
        "technical_signal": "bullish",
    },
    {
        "symbol": "NVDA",
        "name": "NVIDIA Corporation",
        "asset_type": "Equity",
        "currency": "USD",
        "sector": "Semiconductors",
        "price": Decimal("157.75"),
        "change_percent": Decimal("-0.84"),
        "market_cap": Decimal("3860000000000.00"),
        "pe_ratio": Decimal("49.73"),
        "dividend_yield": Decimal("0.03"),
        "fair_value": Decimal("165.00"),
        "technical_signal": "neutral",
    },
    {
        "symbol": "TLT",
        "name": "iShares 20+ Year Treasury Bond ETF",
        "asset_type": "ETF",
        "currency": "USD",
        "sector": "Fixed Income",
        "price": Decimal("88.92"),
        "change_percent": Decimal("0.31"),
        "market_cap": Decimal("51000000000.00"),
        "pe_ratio": Decimal("0.00"),
        "dividend_yield": Decimal("4.22"),
        "fair_value": Decimal("91.40"),
        "technical_signal": "neutral",
    },
]

RECOMMENDATIONS: list[dict[str, Any]] = [
    {
        "symbol": "MSFT",
        "rating": "BUY",
        "score": Decimal("87.50"),
        "rationale": "Strong cash generation and resilient cloud growth; valuation remains elevated.",
        "horizon": "12 months",
        "generated_at": datetime(2026, 6, 29, 8, 0, tzinfo=UTC),
    },
    {
        "symbol": "AAPL",
        "rating": "HOLD",
        "score": Decimal("68.00"),
        "rationale": "Stable services mix offsets a limited near-term margin of safety.",
        "horizon": "12 months",
        "generated_at": datetime(2026, 6, 29, 8, 0, tzinfo=UTC),
    },
    {
        "symbol": "TLT",
        "rating": "BUY",
        "score": Decimal("74.25"),
        "rationale": "Duration exposure may benefit from easing inflation, with meaningful rate risk.",
        "horizon": "6 months",
        "generated_at": datetime(2026, 6, 29, 8, 0, tzinfo=UTC),
    },
]

POLITICAL_EVENTS: list[dict[str, Any]] = [
    {
        "title": "Central bank policy testimony",
        "region": "United States",
        "impact": "high",
        "summary": "Demo scenario for assessing rate-sensitive assets; not a live event feed.",
        "affected_assets": ["TLT", "AAPL", "MSFT"],
        "occurs_at": datetime(2026, 7, 1, 14, 0, tzinfo=UTC),
    },
    {
        "title": "Technology export policy review",
        "region": "Global",
        "impact": "medium",
        "summary": "Illustrative policy-risk event for semiconductor exposure.",
        "affected_assets": ["NVDA"],
        "occurs_at": datetime(2026, 7, 8, 10, 30, tzinfo=UTC),
    },
]

PORTFOLIO: dict[str, Any] = {
    "name": "Основной портфель",
    "base_currency": "USD",
    "as_of": datetime(2026, 6, 29, 12, 0, tzinfo=UTC),
    "positions": [
        {
            "id": 1,
            "symbol": "AAPL",
            "quantity": Decimal("120"),
            "average_purchase_price": Decimal("184.25"),
            "purchase_date": date(2024, 3, 14),
            "currency": "USD",
            "fees": Decimal("25.00"),
            "sector": "Technology",
            "geography": "United States",
        },
        {
            "id": 2,
            "symbol": "MSFT",
            "quantity": Decimal("80"),
            "average_purchase_price": Decimal("401.10"),
            "purchase_date": date(2024, 9, 5),
            "currency": "USD",
            "fees": Decimal("18.00"),
            "sector": "Technology",
            "geography": "United States",
        },
        {
            "id": 3,
            "symbol": "TLT",
            "quantity": Decimal("287.98"),
            "average_purchase_price": Decimal("90.10"),
            "purchase_date": date(2025, 1, 22),
            "currency": "USD",
            "fees": Decimal("12.00"),
            "sector": "Fixed Income",
            "geography": "United States",
        },
    ],
}
